### ISSUE TITLE
I want you to describe the correct copyright to UIIimage+GIF.h and UIImage+GIF.m

### ISSUE THREAD

**Issue by kirou** [larcus94/LBGIFImage#8]
Hi:

Since the copyright that has been described in these file is in the unknown, I want you to describe the correct copyright

 https://github.com/larcus94/LBGIFImage/blob/master/LBGIFImage/UIImage%2BGIF.h#L6
 https://github.com/larcus94/LBGIFImage/blob/master/LBGIFImage/UIImage%2BGIF.m#L6

Although this code is what is used in SDWebImage

 https://github.com/rs/SDWebImage/blob/3.7.5/SDWebImage/UIImage%2BGIF.h#L6
 https://github.com/rs/SDWebImage/blob/3.7.5/SDWebImage/UIImage%2BGIF.m#L6

because the Copyright has become unclear, I think that dangerous as a license.
If described the copyright in this code, we wanted to also fixes SDWebImage side.

thank you.

**Comment by larcus94** [comment]
I fixed this in the latest commit. Check it out and let me know if that is sufficient.

**Comment by kirou** [comment]
Thank you!!  I think I try to convey to SDWebImage side.
